displayName: geoblock
type: middleware
import: github.com/nscuro/traefik-plugin-geoblock
summary: traefik plugin to block or allow requests based on geolocation
testData:
  # It doesn't appear to be possible to get the pilot plugin analyzer
  # to load local files. To prevent errors, the plugin is disabled here.
  # This will cause the plugin to not attempt to load the database file.
  enabled: false
  # databaseFilePath: IP2LOCATION-LITE-DB1.IPV6.BIN
  # allowedCountries: [ "CH", "DE" ]
  # blockedCountries: [ "RU" ]
  # defaultAllow: false
  # allowPrivate: true
  # disallowedStatusCode: 403
  # allowedIPBlocks: ["66.249.64.0/19"]
  # blockedIPBlocks: ["66.249.64.0/24"]
